/**
 * External dependencies
 */
const { qr } = window; // Loaded via block.json.

/**
 * WordPress dependencies
 */
import { Button } from '@wordpress/components';
import { Icon, lock, reusableBlock } from '@wordpress/icons';
import { RawHTML, useEffect, useState } from '@wordpress/element';

//
export default function TOTP( { userRecord } ) {
	const enabledProviders = Object.values( userRecord.record[ '2fa_enabled_providers' ] );
	const totpStatus       = enabledProviders.includes( 'Two_Factor_Totp' ) ? 'enabled' : 'disabled';

	return (
		<>
			{ 'disabled' === totpStatus && <Setup /> }
			{ 'enabled' === totpStatus && <Manage /> }
		</>
	);
}

//
function Setup() {
	const [ totpUrl, setTotpUrl ] = useState( '' );
	const [ qr, setQr ] = useState( false );
	/*
	todo

	use dion pr for rest api endpoint

	have func to save
	after setting this up is done, check if they have backup codes, and if not, redirect them to that screen

	*/

	useEffect( () => {
		setTotpUrl( 'ottpauth://totp/wp.test%3Aiandunn?secret=NQ4XE225LJ3CG2D4EFYCCPTIJESFI4RT&issuer=wp.test' );
		// get from xhr request
		// preload it in php, but only if totp not already active for user since that's the only time we'll show this screen

		const qr = qrcode( 0, 'L' );
		qr.addData( totpUrl );
		qr.make();

		setQr( qr );
	}, [] );

	return (
		<>
			<SetupIntro step="verify-codes" />

			<p>
				Scan this QR code with the authenticator app on your mobile device.

				<Button isLink onClick={ () => console.log( 'show code' ) }>
					Can't scan the code?
				</Button>
			</p>

			<p className="wporg-2fa__qr-code">
				{ ! qr && "Loading..." }

				{ qr &&
					<a href={ totpUrl }>
						<RawHTML>
							{ qr.createSvgTag( 5 ) }
						</RawHTML>
					</a>
				}
			</p>

			<p>
				Then enter the six digit code provided by the app:
			</p>

			<p>
				{/* See https://stackoverflow.com/a/66759105/450127.*/}
				<input type="text" inputMode="numeric" pattern="[0-9]*" placeholder="e.g., 123456" maxLength="6" />
			</p>

			<p>
				Not sure what this screen means? You may need to download Authy or Google Authenticator for your phone
				{/* add links to those. maybe pick different ones> */ }
			</p>

			<p>
				<Button isPrimary>
					Enable
				</Button>

				<Button isSecondary>
					Cancel
				</Button>
			</p>
		</>
	);
}

{/* move to separate file so it can be imported into backup codes */}
function SetupIntro( step = 'verify-codes' ) {
	return (
		<>
			<ul>
				<li>
					<Icon icon={ lock } />
					Verify Codes
				</li>

				<li>
					<Icon icon={ reusableBlock } />
					Backup Codes
				</li>
			</ul>

			<p>
				Two-Step Authentication adds an extra layer of security to your account.
				Once enabled, logging in to WordPress.org will require you to enter a unique passcode
				generated by an app on your mobile device , in addition to your username and password.
			</p>
		</>
	);
}

//
function Manage() {
	return (
		<>
			You've enabled two-step authentication on your account — smart move! When you log in to WordPress.com, you'll need to enter your username and password, as well as a unique passcode generated by an app on your mobile device.

			Switching to a new device? Follow these steps to avoid losing access to your account.
			https://wordpress.com/support/security/two-step-authentication/#moving-to-a-new-device

			Status: Two-step authentication is currently on.
		</>
	);
}
