name: Build and push to build branch.

on:
    push:
        branches: [trunk]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'

            - name: Install all dependencies
              run: |
                  composer install
                  npm install

            - name: Build
              run: npm run build --workspaces

            - name: Trim the repo down to just the plugin files
              run: |
                  rm -rf node_modules
                  rm -rf settings/node_modules
                  rm -rf vendor

            - name: Append build number to version
              run: |
                VER=$( jq -r .version ./settings/build/block.json )
                VER="${VER%%-*}"
                new_file="$(jq --arg ver "$VER-${GITHUB_SHA::7}" '.version = $ver' ./settings/build/block.json)"
                echo -E "$new_file" > ./settings/build/block.json

            - name: Commit and push
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git add * --force
                  git commit -m "Build: ${{ github.sha }}" --allow-empty
                  git push --force origin HEAD:build
