name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  check:
    name: All

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - name: Install NPM dependencies
      run: |
        yarn

    - name: Lint JavaScript
      run: |
        yarn workspaces run lint:js

