name: Test

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [trunk]
  pull_request:

jobs:

  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Install NPM dependencies
        run: npm install

      - name: Start the Docker testing environment
        run: npx wp-env start --xdebug=coverage

      - name: Test PHP
        run: npm test

      - name: Test JS
        run: npm run test:js
